### 
# Base URL
@baseUrl = http://localhost:3000

### 
# Home or welcome page to the API
GET {{baseUrl}} HTTP/1.1
Content-Type: application/json
 
 

###  
# Retrieve diagnosis codes by ID
GET {{baseUrl}}/icd/A000  HTTP/1.1


###  
# List diagnosis codes in batches of 20 by default
GET {{baseUrl}}/icd?limit=2&cursor=  HTTP/1.1 


###  
# Create a new diagnosis code record
POST {{baseUrl}}/icd HTTP/1.1
Content-Type: application/json 

{
  "categoryCode": "A00000000B",
  "diagnosisCode": "1",
  "abbreviatedDescription": "New diseases sars",
  "fullDescription": "sars disease, airbone",
  "categoryTitle": "airborne"
}


###  
# Edit an existing diagnosis code record 
PUT {{baseUrl}}/icd/A00000000B1 HTTP/1.1
Content-Type: application/json 

{
  "categoryCode": "A00000",
  "diagnosisCode": "1",
  "abbreviatedDescription": "Edited - New diseases sars",
  "fullDescription": "Edited - sars disease, airbone",
  "categoryTitle": "Edited - airborne"
}

 

###  
# Delete a diagnosis code by ID
DELETE {{baseUrl}}/icd/A000001  HTTP/1.1

 

###   Uploading ICD CSV files with  diagnosis code records  
POST {{baseUrl}}/icd-upload 
Content-Type: multipart/form-data; boundary=----theDelimiter

------theDelimiter
Content-Disposition: form-data; name="email"

email-address-of-uploader@domain.com
------theDelimiter
Content-Disposition: form-data; name="csv"; filename="2.csv"
Content-Type: text/csv

A00,0,A000,"Cholera due to Vibrio cholerae 01, biovar cholerae","Cholera due to Vibrio cholerae 01, biovar cholerae","Cholera"
A00,1,A001,"Cholera due to Vibrio cholerae 01, biovar eltor","Cholera due to Vibrio cholerae 01, biovar eltor","Cholera"
------theDelimiter--
 

