### 
# Base URL
@baseUrl = http://localhost:3000

### 
# Home or welcome page to the API
GET {{baseUrl}} HTTP/1.1
Content-Type: application/json
 
 

###  
# Retrieve diagnosis codes by ID
GET {{baseUrl}}/icd/A000  HTTP/1.1


###  
# List diagnosis codes in batches of 20 by default
GET {{baseUrl}}/icd?limit=2&cursor=  HTTP/1.1 


###  
# Create a new diagnosis code record
POST {{baseUrl}}/icd HTTP/1.1
Content-Type: application/json 

{
  "categoryCode": "A00000000B",
  "diagnosisCode": "1",
  "abbreviatedDescription": "New diseases sars",
  "fullDescription": "sars disease, airbone",
  "categoryTitle": "airborne"
}


###  
# Edit an existing diagnosis code record 
PUT {{baseUrl}}/icd/A00000000B1 HTTP/1.1
Content-Type: application/json 

{
  "categoryCode": "A00000",
  "diagnosisCode": "1",
  "abbreviatedDescription": "Edited - New diseases sars",
  "fullDescription": "Edited - sars disease, airbone",
  "categoryTitle": "Edited - airborne"
}

 

###  
# Delete a diagnosis code by ID
DELETE {{baseUrl}}/icd/A000001  HTTP/1.1

 

###   Uploading ICD CSV files with  diagnosis code records  
POST {{baseUrl}}/icd-upload 
X-Notification-Email: demo@github.com
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="records"; filename="my_image.csv"
Content-Type: text/csv

< /path/to/file.csv
--boundary-- 

